# Generated by Django 5.1.4 on 2025-01-10 02:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('published_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('is_outofservices', models.BooleanField(default=False)),
                ('is_comments', models.BooleanField(default=True)),
                ('fp_num', models.IntegerField(default=16)),
                ('fp_max', models.IntegerField(default=999)),
                ('tp_num', models.IntegerField(default=16)),
                ('tp_max', models.IntegerField(default=999)),
                ('your_comment', models.TextField(max_length=200)),
                ('published_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.content')),
            ],
        ),
    ]
