# Generated by Django 5.1.4 on 2025-01-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.TextField(max_length=200),
        ),
    ]
