# Generated by Django 5.1.4 on 2025-01-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
